apiVersion: apps/v1
kind: Deployment
metadata:
  name: ditest
  namespace: prod
  labels:
    app: ditest
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ditest
      env: prod
  template:
    metadata:
      labels:
        app: ditest
        env: prod
    spec:
      containers:
      - name: ditest
        image: ghananauticalinfo/ditest:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ditest-service
  namespace: prod
spec:
  selector:
    app: ditest
    env: prod
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ditest-ingress
  namespace: prod
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - snapper.ghananautical.info
    secretName: snapper-tls
  rules:
  - host: snapper.ghananautical.info
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ditest-service
            port:
              number: 80