# File: .github/workflows/deploy-prod.yml
name: Build and Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      confirm_deployment:
        description: 'Type "deploy-to-production" to confirm'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghananauticalinfo/ditest:latest
            ghananauticalinfo/ditest:prod-${{ github.sha }}
          build-args: |
            ENVIRONMENT=production
          
  deploy-prod:
    needs: build-and-push
    runs-on: ubuntu-latest
    # Only run if triggered via workflow_dispatch with correct confirmation
    if: |
      github.event_name == 'workflow_dispatch' && 
      github.event.inputs.confirm_deployment == 'deploy-to-production' || 
      github.event_name == 'push'
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
      - name: Save DigitalOcean kubeconfig
        run: |
          echo "Available Kubernetes clusters:"
          doctl kubernetes cluster list
          
          # Get the cluster ID instead of relying on exact name match
          CLUSTER_ID=$(doctl kubernetes cluster list --format ID,Name --no-header | grep ${{ secrets.PROD_CLUSTER_NAME }} | awk '{print $1}')
          
          if [ -z "$CLUSTER_ID" ]
          then
            echo "Could not find cluster with name containing ${{ secrets.PROD_CLUSTER_NAME }}"
            echo "Please check the PROD_CLUSTER_NAME secret and available clusters listed above"
            exit 1
          else
            echo "Found cluster ID: $CLUSTER_ID"
            doctl kubernetes cluster kubeconfig save $CLUSTER_ID
          fi
      
      - name: Deploy to Kubernetes
        run: |
          # Replace image tag in deployment file
          sed -i "s|yourdockerhubusername/ditest:latest|ghananauticalinfo/ditest:prod-${{ github.sha }}|g" k8s/prod/deployment.yaml
          
          # Apply Kubernetes manifests
          kubectl apply -f k8s/prod/deployment.yaml
          kubectl rollout status deployment/ditest -n prod