# File: .github/workflows/deploy-test.yml
name: Build and Deploy to Test

on:
  push:
    branches: [ develop, feature/*, bugfix/* ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_ENV
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghananauticalinfo/ditest:test-${{ env.BRANCH_NAME }}
          build-args: |
            ENVIRONMENT=test
          
  deploy-test:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_ENV
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.TEST_CLUSTER_NAME }}
      
      - name: Deploy to Kubernetes
        run: |
          # Replace image tag in deployment file
          sed -i "s|yourdockerhubusername/ditest:latest|ghananauticalinfo/ditest:test-${{ env.BRANCH_NAME }}|g" k8s/test/deployment.yaml
          
          # Apply Kubernetes manifests
          kubectl apply -f k8s/test/deployment.yaml
          kubectl rollout status deployment/ditest-test -n test